version: "3"

services:
  # "cubetl service" = "cubetls"
  cubetls:
    build: .
    environment:
      - PYTHONDONTWRITEBYTECODE=true
      - PYTHONPATH=.
    volumes:
      # mount current directory so that changes in files are reflected
      # in the running envirinment
      - .:/app
    # Open up ports, hopefully not in conflict with any other you may be running
    # This allows cubes to show up on port 5005, and an HTTP server on 8008.
    ports:
      - "5005:5000"
      - "8008:8000"
